wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.18.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1730954686
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 4
      - 13
      - 23
      - 42
      - 55
      4: 3.10.14
      5: 0.18.5
      8:
      - 5
      13: linux-x86_64
